# Server port
server:
  port: 8080
  ssl:
    key-store-type: PKCS12 # The format used for the keystore
    key-store: classpath:keystore.p12 # The path to the keystore containing the certificate
    key-store-password: password # The password used to generate the certificate
    key-alias: tomcat

security:
  require-ssl: true # Tell Spring Security (if used) to require requests over HTTPS

spring:
  datasource:
    url: jdbc:postgresql://13.229.132.148:5432/xbank
    username: root
    password: xbank@123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

# JWT properties
app:
  cache:
    logoutToken:
      maxSize: 1000
  jwt:
    header: Authorization
    header-prefix: Bearer
    secret: xbank
    expiration: 600000
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 2592000000
  velocity:
    templates:
      location: /templates/

